### ISSUE TITLE
using `a` in adds

### ISSUE THREAD

**Issue by rustamidastan** [kozimov786/namanganliklar24#1]
![image](https://user-images.githubusercontent.com/77572961/115664519-606c6500-a35b-11eb-89b0-fc7db3cf28c0.png)
Here `img` should be in `a`.

**Comment by kozimov786** [comment]
> ![image](https://user-images.githubusercontent.com/77572961/115664519-606c6500-a35b-11eb-89b0-fc7db3cf28c0.png)
> Here `img` should be in `a`.

i forgot to use it
